{{- if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: {{ .Values.backend.name }}
                port:
                  number: 80
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Values.frontend.name }}
                port:
                  number: 80
{{- end}}
