apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo-app-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
  - git:
      repoURL: https://github.com/FaresMirza/todo-app-devops
      revision: main
      files:
        - path: helm/*/config.yaml

  template:
    metadata:
      name: "{{.app.name}}"
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    spec:
      project: "{{.app.project}}"
      source:
        repoURL: https://github.com/FaresMirza/todo-app-devops
        targetRevision: main
        path: "{{.app.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.app.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=false