apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.service.port}}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres
