apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: todo-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http