apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-backend-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app: todo-frontend-prereq
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: wait-for-backend
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for Backend API to be ready..."
          until curl -f http://todo-api-service:80/health || curl -f http://todo-api-service:80 ; do
            echo "Backend API is not ready yet... waiting 10 seconds"
            sleep 10
          done
          echo "Backend API is ready! Frontend can start."
  backoffLimit: 10