apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: todo-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    app: todo-frontend