apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  replicas: {{.Values.app.replicas}}
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: {{.Values.app.image}}
          ports:
            - containerPort: {{.Values.app.port}}
              name: http
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:{{.Values.app.port}}"
            - name: ConnectionStrings__DefaultConnection
              value: "Host={{.Values.database.host}};Port={{.Values.database.port}};Database={{.Values.database.name}};Username={{.Values.database.username}};Password=todopassword"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
