apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-backend-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: todo-backend
spec:
  project: default
  source:
    repoURL: https://github.com/FaresMirza/todo-app-devops
    targetRevision: main
    path: helm/todo-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true