apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-postgres-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: todo-postgres
spec:
  project: default
  source:
    repoURL: https://github.com/FaresMirza/todo-app-devops
    targetRevision: main
    path: helm/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true