app:
  name: todo-api
  image: acrtodoappdev001.azurecr.io/todo-api:v16
  port: 8080
  replicas: 3

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: todo.local

database:
  host: postgres
  port: 5432
  name: tododb
  username: todouser
