apiVersion: v2
name: todo-frontend
description: Todo Frontend Helm chart
version: 0.1.0
appVersion: "1.0"
maintainers:
  - name: FaresMirza
    email: fares@example.com
keywords:
  - todo
  - frontend
  - angular
  - kubernetes
sources:
  - https://github.com/FaresMirza/todo-app-devops