backend:
  name: todo-api
<<<<<<< HEAD
  image: acrtodoappdev001.azurecr.io/todo-api:v22
  port: 80
=======
  image: acrtodoappdev001.azurecr.io/todo-api:v22
  port: 8080
>>>>>>> d63644ee (.)
  replicas: 3

frontend:
  name: todo-frontend
  image: acrtodoappdev001.azurecr.io/todo-frontend:v53
  port: 80
  replicas: 2



service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: todo.local

database:
  host: postgres
  port: 5432
  name: tododb
  username: todouser
  password: todopassword

