backend:
  name: todo-api
  image: acrtodoappdev001.azurecr.io/todo-api:v19
  port: 8080
  replicas: 3

frontend:
  name: todo-frontend
  image: acrtodoappdev001.azurecr.io/todo-frontend:v26
  port: 80
  replicas: 2



service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: todo.local

database:
  host: postgres
  port: 5432
  name: tododb
  username: todouser


