backend:
  name: todo-api
  image: faresmirza/todo-api:v32
  port: 8080
  replicas: 2

service:
  type: ClusterIP
  port: 80

database:
  host: postgres
  port: 5432
  name: tododb
  username: todouser
  password: todopassword