name: CI/CD Pipeline For Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: "0"
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-api:v${{ github.run_number }} ./backend

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-api:v${{ github.run_number }}

  update-helm:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Helm values.yaml
        run: |
          # Update the image tag in Helm values
          sed -i 's|image: .*/todo-api:.*|image: ${{ secrets.DOCKER_USERNAME }}/todo-api:v${{ github.run_number }}|' helm/todo-backend/values.yaml

          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Commit and push changes
          git add helm/todo-backend/values.yaml
          git commit -m "Update backend image tag to v${{ github.run_number }}" || exit 0
          git pull --rebase origin main
          git push

      - name: Trigger ArgoCD Sync
        run: |
          # For local development, trigger ArgoCD sync via webhook
          # ArgoCD webhook URL for local cluster (using port-forward)
          curl -X POST "http://localhost:8080/api/webhook" \
            -H "Content-Type: application/json" \
            -d '{
              "repository": {
                "url": "https://github.com/FaresMirza/todo-app-devops"
              },
              "ref": "refs/heads/main"
            }' || echo "Webhook call failed, ArgoCD will sync on next poll (3 minutes)"