name: CI/CD Pipeline For Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: "0"
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/todo-api:v${{ github.run_number }} ./backend

      - name: Save image as artifact
        run: |
          docker save ${{ secrets.ACR_LOGIN_SERVER }}/todo-api:v${{ github.run_number }} | gzip > image.tar.gz
        # رفع الصورة كـ artifact مؤقت
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: todo-api-image
          path: image.tar.gz

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: todo-api-image

      - name: Load Docker image
        run: |
          gunzip -c image.tar.gz | docker load

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/todo-api:v${{ github.run_number }}

  update-helm:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Helm values.yaml
        run: |
          sed -i 's|image: .*/todo-api:.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/todo-api:v${{ github.run_number }}|' helm/todo-app/values.yaml

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add helm/todo-app/values.yaml
          git commit -m "Update image tag to v${{ github.run_number }}" || echo "No changes to commit"
          git push