name: Build Docker Image

on:
  push:
    branches: [main]
    paths:
      - "app/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: "0"
          ACR_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          docker build -t ${ACR_SERVER}/todo-api:v${{ github.run_number }} ./app

      - name: Push Docker image
        env:
          ACR_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          docker push ${ACR_SERVER}/todo-api:v${{ github.run_number }}