name: CI/CD Pipeline For Frontend

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: "0"
        run: |
          docker build -t acrtodoappdev001.azurecr.io/todo-frontend:v${{ github.run_number }} ./frontend

      - name: Push Docker image
        run: |
          docker push acrtodoappdev001.azurecr.io/todo-frontend:v${{ github.run_number }}

  update-helm:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Helm values.yaml
        run: |
          # Update the image tag in Helm values
          sed -i 's|image: acrtodoappdev001.azurecr.io/todo-frontend:.*|image: acrtodoappdev001.azurecr.io/todo-frontend:v${{ github.run_number }}|' helm/todo-app/values.yaml

          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git pull --rebase origin main

          # Commit and push changes
          git add helm/todo-app/values.yaml
          git commit -m "Update frontend image tag to v${{ github.run_number }}" || exit 0
          git push